"use client";

import { useEffect, useState } from "react";
import EvolveShell, { Header } from "@/components/evolve-shell";
import { Bell, Check, Globe2, LockKeyhole, Moon, Save, ShieldCheck, SlidersHorizontal, Sun, UserRound } from "lucide-react";

const sections = [["Perfil", UserRound], ["Objetivos diarios", SlidersHorizontal], ["Notificaciones", Bell], ["Privacidad", LockKeyhole], ["Apariencia", Moon]] as const;
const notificationItems = [["Recordatorios diarios", "Recibe un aviso para registrar tus comidas y actividad."], ["Resumen semanal", "Te enviaremos tu evolución cada domingo."], ["Consejos del Coach", "Sugerencias adaptadas a tus objetivos."]];

export default function ConfiguracionPage() { const [section, setSection] = useState("Perfil"); const [toggles, setToggles] = useState([true, true, false]); const [saved, setSaved] = useState(false); const save = () => { setSaved(true); window.setTimeout(() => setSaved(false), 2200); }; return <EvolveShell active="Configuración"><Header eyebrow="PREFERENCIAS" title="Configuración" subtitle="Personaliza tu experiencia en Evolve." action="Guardar cambios" onAdd={save} /><div className="settings-layout"><aside className="settings-nav" aria-label="Secciones de configuración">{sections.map(([label, Icon]) => <button className={section === label ? "selected" : ""} onClick={() => setSection(label)} key={label}><Icon size={15} /> {label}</button>)}</aside><section className="settings-content">{section === "Perfil" && <ProfileSettings />}{section === "Objetivos diarios" && <GoalsSettings />}{section === "Notificaciones" && <NotificationSettings toggles={toggles} setToggles={setToggles} />}{section === "Privacidad" && <PrivacySettings />}{section === "Apariencia" && <AppearanceSettings />}</section></div>{saved && <div className="settings-saved"><Save size={14} /> Cambios guardados</div>}</EvolveShell>; }
function SectionHeading({ eyebrow, title, icon }: { eyebrow: string; title: string; icon?: React.ReactNode }) { return <div className="settings-heading"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div>{icon}</div>; }
function ProfileSettings() { return <><div className="settings-section"><SectionHeading eyebrow="CUENTA" title="Información personal" /><div className="profile-form"><div className="settings-avatar">A</div><label>Nombre<input defaultValue="Alejandro" /></label><label>Email<input defaultValue="alejandro@email.com" /></label></div></div><div className="settings-section"><SectionHeading eyebrow="IDIOMA" title="Preferencias regionales" icon={<Globe2 size={16} />} /><div className="settings-fields"><label>Idioma<select defaultValue="Español"><option>Español</option><option>English</option></select></label><label>Unidades<select defaultValue="Métricas"><option>Métricas</option><option>Imperiales</option></select></label></div></div></>; }
function GoalsSettings() { return <div className="settings-section"><SectionHeading eyebrow="SEGUIMIENTO" title="Objetivos diarios" /><p className="settings-description">Estos objetivos aparecen en tu resumen, diario y recomendaciones del Coach.</p><div className="settings-fields"><label>Objetivo de calorías<input defaultValue="2.200 kcal" /></label><label>Objetivo de pasos<input defaultValue="10.000 pasos" /></label><label>Objetivo de peso<input defaultValue="70,0 kg" /></label><label>Objetivo de proteína<input defaultValue="145 g" /></label></div></div>; }
function NotificationSettings({ toggles, setToggles }: { toggles: boolean[]; setToggles: (value: boolean[]) => void }) { return <div className="settings-section"><SectionHeading eyebrow="AVISOS" title="Notificaciones" icon={<Bell size={16} />} /><div className="toggle-list">{notificationItems.map(([title, description], index) => <div className="toggle-row" key={title}><div><strong>{title}</strong><small>{description}</small></div><button className={`toggle ${toggles[index] ? "on" : ""}`} onClick={() => setToggles(toggles.map((value, itemIndex) => itemIndex === index ? !value : value))} aria-label={`${title}: ${toggles[index] ? "activado" : "desactivado"}`}><i /></button></div>)}</div></div>; }
function PrivacySettings() { return <><div className="settings-section"><SectionHeading eyebrow="DATOS Y PRIVACIDAD" title="Tu información está bajo tu control" icon={<ShieldCheck size={16} />} /><div className="privacy-items"><div><strong>Perfil privado</strong><small>Solo tú puedes ver tus datos de salud y evolución.</small><Check size={15} /></div><div><strong>Datos locales</strong><small>El historial se conserva de forma segura en tu cuenta.</small><Check size={15} /></div><div><strong>Sin publicidad personalizada</strong><small>No usamos tus datos para mostrar anuncios.</small><Check size={15} /></div></div></div><div className="settings-section danger-section"><SectionHeading eyebrow="ZONA DE CUENTA" title="Gestionar mis datos" /><p className="settings-description">Puedes descargar una copia de tus datos o solicitar su eliminación en cualquier momento.</p><button className="danger-button">Solicitar exportación de datos</button></div></>; }
function AppearanceSettings() { const [theme, setTheme] = useState<"Oscuro" | "Claro">(() => typeof window !== "undefined" && window.localStorage.getItem("evolve-theme") === "Claro" ? "Claro" : "Oscuro"); useEffect(() => { document.documentElement.classList.toggle("light", theme === "Claro"); window.localStorage.setItem("evolve-theme", theme); }, [theme]); return <div className="settings-section"><SectionHeading eyebrow="INTERFAZ" title="Apariencia" icon={theme === "Claro" ? <Sun size={16} /> : <Moon size={16} />} /><p className="settings-description">Elige cómo quieres ver Evolve en tus dispositivos.</p><div className="theme-options"><button className={theme === "Oscuro" ? "selected" : ""} onClick={() => setTheme("Oscuro")}><Moon size={18} /><strong>Oscuro</strong><small>Ideal para la noche</small></button><button className={theme === "Claro" ? "selected" : ""} onClick={() => setTheme("Claro")}><Sun size={18} /><strong>Claro</strong><small>Luminoso y limpio</small></button><button disabled><SlidersHorizontal size={18} /><strong>Sistema</strong><small>Próximamente</small></button></div></div>; }
