"use client";

import { useState } from "react";
import EvolveShell, { Header } from "@/components/evolve-shell";
import { ArrowUp, Bot, Check, Dumbbell, HeartPulse, MessageCircle, Sparkles, Utensils } from "lucide-react";

const prompts = [["Analiza mi progreso", HeartPulse], ["¿Cuántas calorías he comido?", Utensils], ["Crea un entrenamiento", Dumbbell], ["Dame un consejo", Sparkles]] as const;

export default function CoachPage() { const [message, setMessage] = useState(""); const [sent, setSent] = useState(false); const send = () => { if (!message.trim()) return; setSent(true); setMessage(""); }; return <EvolveShell active="IA Coach"><Header eyebrow="ASISTENTE PERSONAL" title="IA Coach" subtitle="Tu acompañante inteligente para avanzar con confianza." action="Nueva conversación" /><div className="coach-layout"><section className="coach-chat"><div className="coach-chat-head"><div className="coach-avatar"><Bot size={20} /></div><div><h2>Evolve Coach</h2><span><i /> En línea · Conoce tu progreso</span></div></div><div className="coach-messages"><div className="coach-message bot"><span>Hola, Alejandro 👋</span><p>He revisado tu evolución de esta semana. Vas muy bien: has perdido 1,2 kg y mantienes una constancia del 82%.</p><small>09:41</small></div>{sent && <div className="coach-message user"><p>Gracias, quiero seguir mejorando.</p><small>Ahora</small></div>}<div className="coach-message bot"><span>¿En qué te ayudo hoy?</span><p>Puedo analizar tus datos, ajustar tus objetivos o prepararte un plan adaptado a tu día.</p></div></div><div className="coach-input"><input value={message} onChange={(event) => setMessage(event.target.value)} onKeyDown={(event) => event.key === "Enter" && send()} placeholder="Escribe tu pregunta..." aria-label="Pregunta para IA Coach" /><button onClick={send} aria-label="Enviar pregunta"><ArrowUp size={16} /></button></div></section><aside className="coach-aside"><section className="coach-card"><div className="panel-heading"><h2>Accesos rápidos</h2><MessageCircle size={15} /></div><div className="quick-prompts">{prompts.map(([label, Icon]) => <button key={label} onClick={() => setMessage(label)}><Icon size={14} />{label}</button>)}</div></section><section className="coach-card coach-insight"><div className="insight-title"><Sparkles size={15} /><span>INSIGHT DE HOY</span></div><h2>Tu mejor momento para entrenar</h2><p>Según tus registros, sueles completar más sesiones por la tarde. Reserva 45 minutos hoy para mantener tu racha.</p><div className="insight-meta"><Check size={13} /> Basado en tus últimos 30 días</div></section></aside></div></EvolveShell>; }
