"use client";

import Link from "next/link";
import { Activity, Bell, CalendarDays, ChevronDown, ChevronRight, CircleHelp, Dumbbell, Flame, Footprints, HeartPulse, Home, Plus, Scale, Settings, Sparkles, Target, Utensils } from "lucide-react";

const navItems = [[Home, "Resumen", "/"], [CalendarDays, "Diario", "/diario"], [Utensils, "Nutrición", "/nutricion"], [Scale, "Peso y medidas", "/peso-y-medidas"], [Dumbbell, "Entrenamiento", "/entrenamiento"], [Activity, "Galería", "/galeria"], [HeartPulse, "Estadísticas", "/estadisticas"], [Target, "Objetivos", "/objetivos"], [Sparkles, "IA Coach", "/ia-coach"]] as const;

export default function EvolveShell({ active, children }: { active: string; children: React.ReactNode }) {
  return <div className="app-shell"><aside className="sidebar"><Link href="/" className="brand"><span className="brand-mark">E</span>VOLVE</Link><nav aria-label="Navegación principal">{navItems.map(([Icon, label, href]) => <Link className={`nav-item ${active === label ? "active" : ""}`} href={href} key={label}><Icon size={15} /><span>{label}</span></Link>)}</nav><div className="sidebar-bottom"><Link href="/configuracion" className="nav-item"><Settings size={15} /><span>Configuración</span></Link><div className="profile"><div className="avatar">A</div><div><strong>Alejandro</strong><small>Ver perfil</small></div><ChevronRight size={14} /></div></div></aside><main className="dashboard">{children}</main></div>;
}

export function Header({ eyebrow, title, subtitle, action, onAdd }: { eyebrow: string; title: string; subtitle: string; action: string; onAdd?: () => void }) { return <header className="topbar"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="subtle">{subtitle}</p></div><div className="header-actions"><button className="add-button" onClick={onAdd}><Plus size={16} /> {action}</button><button className="icon-button" aria-label="Notificaciones"><Bell size={17} /></button><button className="icon-button" aria-label="Ayuda"><CircleHelp size={17} /></button><button className="user-chip">A <ChevronDown size={14} /></button></div></header>; }

export function Panel({ title, children, action = "Ver detalles" }: { title: string; children?: React.ReactNode; action?: string }) { return <section className="panel"><div className="panel-heading"><h2>{title}</h2><button>{action}<ChevronRight size={12} /></button></div>{children}</section>; }
export function ActivityRow({ icon, label, value, goal, color }: { icon: React.ReactNode; label: string; value: string; goal?: string; color: string }) { return <div className="activity-row"><div className={`activity-icon ${color}`}>{icon}</div><span>{label}</span><strong>{value} <small>{goal}</small></strong></div>; }

export function DiaryContent({ onAdd }: { onAdd: () => void }) { const meals = [["☕", "Desayuno", "08:30", "Avena con frutos rojos · Café con leche", "542", "orange"], ["🥗", "Comida", "14:10", "Pechuga de pollo · Arroz blanco · Ensalada", "712", "green"], ["🍎", "Merienda", "17:30", "Yogur natural con nueces", "210", "blue"], ["＋", "Cena", "Sin registrar", "Añade tu cena para cerrar el día", "-", "purple"]]; return <><Header eyebrow="DIARIO ALIMENTARIO" title="Viernes, 7 de junio" subtitle="Registra lo que comes y mantén tu progreso en marcha." action="Añadir alimento" onAdd={onAdd} /><div className="date-strip"><button aria-label="Día anterior">‹</button><div><small>JUNIO 2024</small><strong>Viernes 7</strong></div><button aria-label="Día siguiente">›</button></div><section className="diary-summary"><div><span>Calorías consumidas</span><strong>1.464 <small>/ 2.200 kcal</small></strong><div className="bar"><i style={{ width: "67%" }} /></div><em>736 kcal restantes</em></div><div className="diary-ring"><div><strong>67%</strong><span>objetivo</span></div></div><div className="macro-mini"><span>Proteínas <b>92 / 145 g</b></span><i><u style={{ width: "63%" }} /></i><span>Carbohidratos <b>136 / 220 g</b></span><i><u style={{ width: "62%" }} /></i><span>Grasas <b>48 / 73 g</b></span><i><u style={{ width: "66%" }} /></i></div></section><div className="diary-layout"><section className="meal-column"><div className="section-title"><div><p className="eyebrow">REGISTRO DEL DÍA</p><h2>Tus comidas</h2></div><span>3 de 4 registradas</span></div>{meals.map(([icon, name, time, foods, calories, tone]) => <article className={`meal-card ${name === "Cena" ? "empty" : ""}`} key={name}><div className={`meal-icon ${tone}`}>{icon}</div><div className="meal-info"><div><h3>{name}</h3><time>{time}</time></div><p>{foods}</p></div><strong className="meal-calories">{calories}<small>{calories === "-" ? "" : " kcal"}</small></strong><button className="meal-more" aria-label={`Opciones de ${name}`}>•••</button></article>)}</section><aside className="diary-aside"><section className="side-panel"><div className="panel-heading"><h2>Hidratación</h2><span>1,5 / 2,0 L</span></div><div className="water-glasses"><span className="filled">▰</span><span className="filled">▰</span><span className="filled">▰</span><span className="filled">▰</span><span className="filled">▰</span><span>▰</span><span>▰</span><span>▰</span></div><p>Te faltan 2 vasos para alcanzar tu objetivo.</p><button className="outline-button" onClick={onAdd}><Plus size={14} /> Añadir vaso</button></section><section className="side-panel"><div className="panel-heading"><h2>Actividad diaria</h2><ChevronRight size={14} /></div><ActivityRow icon={<Footprints />} label="Pasos" value="8.432" goal="/10.000" color="blue" /><ActivityRow icon={<Flame />} label="Quemadas" value="520" goal="kcal" color="orange" /></section></aside></div></>; }
