"use client";

import { useState } from "react";
import EvolveShell, { Header } from "@/components/evolve-shell";
import { CalendarDays, ChevronDown, Grid2X2, Images, Plus } from "lucide-react";

const photos = [
  { month: "Junio 2024", date: "7 JUN", image: "https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=700&q=80", label: "Actual" },
  { month: "Junio 2024", date: "1 JUN", image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=700&q=80", label: "" },
  { month: "Mayo 2024", date: "14 MAY", image: "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&w=700&q=80", label: "" },
  { month: "Mayo 2024", date: "1 MAY", image: "https://images.unsplash.com/photo-1583454155184-870a1f63aebc?auto=format&fit=crop&w=700&q=80", label: "" },
  { month: "Abril 2024", date: "18 ABR", image: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=700&q=80", label: "" },
  { month: "Abril 2024", date: "2 ABR", image: "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&w=700&q=80", label: "" },
];

export default function GaleriaPage() { const [mode, setMode] = useState("Fotos"); const [angle, setAngle] = useState("Frontal"); return <EvolveShell active="Galería"><Header eyebrow="EVOLUCIÓN VISUAL" title="Tu galería" subtitle="Compara tu progreso con el paso del tiempo." action="Añadir foto" /><div className="gallery-toolbar"><div className="gallery-tabs"><button className={mode === "Fotos" ? "selected" : ""} onClick={() => setMode("Fotos")}><Images size={14} /> Fotos</button><button className={mode === "Comparar" ? "selected" : ""} onClick={() => setMode("Comparar")}><Grid2X2 size={14} /> Comparar</button></div><div className="gallery-filter"><CalendarDays size={13} /> Junio 2024 <ChevronDown size={13} /></div></div>{mode === "Fotos" ? <section className="gallery-months"><div className="gallery-intro"><div><p className="eyebrow">TU EVOLUCIÓN</p><h2>Registro fotográfico</h2></div><span>6 fotos · Última actualización hoy</span></div>{["Junio 2024", "Mayo 2024", "Abril 2024"].map((month) => <div className="month-group" key={month}><h3>{month}</h3><div className="photo-grid">{photos.filter((photo) => photo.month === month).map((photo) => <article className="photo-card" key={photo.date}><div className="photo-image" style={{ backgroundImage: `url(${photo.image})` }}><span>{photo.date}</span>{photo.label && <b>{photo.label}</b>}</div><div className="photo-meta"><strong>{photo.date === "7 JUN" ? "75,4 kg" : photo.date === "1 JUN" ? "76,6 kg" : ""}</strong><button aria-label={`Opciones de foto del ${photo.date}`}>•••</button></div></article>)}</div></div>)}</section> : <CompareView angle={angle} setAngle={setAngle} />}</EvolveShell>; }
function CompareView({ angle, setAngle }: { angle: string; setAngle: (angle: string) => void }) { const image = "https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=900&q=80"; return <section className="compare-view"><div className="compare-heading"><div><p className="eyebrow">COMPARAR FOTOS</p><h2>Tu evolución visual</h2><p className="subtle">Selecciona dos fechas para ver tus cambios.</p></div><button className="save-button">Guardar comparación</button></div><div className="compare-selectors"><button>01/04/2024 <ChevronDown size={13} /></button><span>VS</span><button>07/06/2024 <ChevronDown size={13} /></button></div><div className="compare-photos"><div style={{ backgroundImage: `url(${image})` }}><span>01/04/2024</span></div><div style={{ backgroundImage: `url(${image})` }}><span>07/06/2024</span></div></div><div className="angle-tabs">{["Frontal", "Lateral", "Trasera"].map((item) => <button className={angle === item ? "selected" : ""} key={item} onClick={() => setAngle(item)}>{item}</button>)}</div><div className="compare-note"><Plus size={14} /><span>La comparación muestra una diferencia de <strong>-4,6 kg</strong> entre ambas fechas.</span></div></section>; }
