"use client";

import { useState } from "react";
import EvolveShell, { Header } from "@/components/evolve-shell";
import { Activity, ChevronLeft, ChevronRight, Flame, Footprints, Plus, Scale } from "lucide-react";

const days = [{ day: 27, kcal: "1.980", burned: "420", weight: "76,6", tone: "good" }, { day: 28, kcal: "2.110", burned: "310", weight: "76,4", tone: "good" }, { day: 29, kcal: "1.850", burned: "520", weight: "76,2", tone: "good" }, { day: 30, kcal: "2.040", burned: "390", weight: "76,0", tone: "good" }, { day: 31, kcal: "1.920", burned: "460", weight: "75,8", tone: "good" }, { day: 1, kcal: "2.080", burned: "280", weight: "75,6", tone: "good" }, { day: 2, kcal: "1.760", burned: "510", weight: "75,5", tone: "good" }, { day: 3, kcal: "1.920", burned: "440", weight: "75,6", tone: "good" }, { day: 4, kcal: "2.140", burned: "320", weight: "75,5", tone: "good" }, { day: 5, kcal: "1.880", burned: "520", weight: "75,6", tone: "good" }, { day: 6, kcal: "1.730", burned: "480", weight: "75,4", tone: "good" }, { day: 7, kcal: "1.464", burned: "520", weight: "75,4", tone: "today" }];

export default function DiarioPage() { const [selectedDay, setSelectedDay] = useState(7); const selected = days.find((day) => day.day === selectedDay) ?? days[days.length - 1]; return <EvolveShell active="Diario"><Header eyebrow="DIARIO · JUNIO 2024" title="Tu calendario" subtitle="Consulta tus comidas, actividad y evolución día a día." action="Añadir registro" /><div className="diary-calendar-toolbar"><button><ChevronLeft size={14} /></button><strong>Junio 2024</strong><button><ChevronRight size={14} /></button><span className="calendar-view-label">Vista mensual</span></div><section className="calendar-layout"><div className="calendar-card"><div className="calendar-weekdays">{["LUN", "MAR", "MIÉ", "JUE", "VIE", "SÁB", "DOM"].map((day) => <span key={day}>{day}</span>)}</div><div className="calendar-grid"><span className="calendar-empty">27</span><span className="calendar-empty">28</span><span className="calendar-empty">29</span><span className="calendar-empty">30</span>{days.slice(4).map((day) => <button className={`calendar-day ${day.day === selectedDay ? "selected" : ""} ${day.tone}`} onClick={() => setSelectedDay(day.day)} key={day.day}><b>{day.day}</b><small><Flame size={10} /> {day.kcal}</small><small><Activity size={10} /> {day.burned} kcal</small><em><Scale size={9} /> {day.weight} kg</em></button>)}</div><div className="calendar-legend"><span><i className="legend-dot complete" /> Día registrado</span><span><i className="legend-dot today-dot" /> Seleccionado</span><span><i className="legend-dot empty-dot" /> Sin datos</span></div></div><aside className="selected-day-panel"><p className="eyebrow">DETALLE DEL DÍA</p><h2>Viernes {selected.day} de junio</h2><div className="day-total"><span>Calorías consumidas</span><strong>{selected.kcal} <small>/ 2.200 kcal</small></strong><div className="bar"><i style={{ width: `${Math.min(Number(selected.kcal.replace(".", "")) / 22, 100)}%` }} /></div></div><div className="selected-stats"><div><Flame size={15} /><span>Gastadas<strong>{selected.burned} kcal</strong></span></div><div><Footprints size={15} /><span>Pasos<strong>8.432</strong></span></div><div><Scale size={15} /><span>Peso<strong>{selected.weight} kg</strong></span></div></div><div className="day-summary"><span>Registro de comidas</span><strong>{selected.day === 7 ? "3 de 4" : "4 de 4"} comidas</strong><small>{selected.day === 7 ? "Cena pendiente de registrar" : "Día completado"}</small></div><button className="outline-button"><Plus size={14} /> Ver detalle del día</button></aside></section><div className="calendar-note"><Activity size={15} /><span>Cada día muestra encima de la fecha tus calorías consumidas y gastadas para que puedas ver tu balance de un vistazo.</span></div></EvolveShell>; }
